// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKi8B1Yx7V8FzbXBz-Z8stj2Y8VRxkhP0',
    appId: '1:727175749515:web:08186c48f29c03d354198e',
    messagingSenderId: '727175749515',
    projectId: 'business-profile-app-7ab80',
    authDomain: 'business-profile-app-7ab80.firebaseapp.com',
    storageBucket: 'business-profile-app-7ab80.firebasestorage.app',
    measurementId: 'G-9YYN8HVJ3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcCveSAQYh9OPDaBHgyp7v6js_CcloPdI',
    appId: '1:727175749515:android:93152f0d1b7c0cd854198e',
    messagingSenderId: '727175749515',
    projectId: 'business-profile-app-7ab80',
    storageBucket: 'business-profile-app-7ab80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtlsKWqFaGesPi78S5HK86si-KK6vSyJc',
    appId: '1:727175749515:ios:53d7da4da460c43354198e',
    messagingSenderId: '727175749515',
    projectId: 'business-profile-app-7ab80',
    storageBucket: 'business-profile-app-7ab80.firebasestorage.app',
    iosClientId: '727175749515-h2v6plbhde561oinu8s4tcftr8h01qtq.apps.googleusercontent.com',
    iosBundleId: 'com.example.reviewmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtlsKWqFaGesPi78S5HK86si-KK6vSyJc',
    appId: '1:727175749515:ios:53d7da4da460c43354198e',
    messagingSenderId: '727175749515',
    projectId: 'business-profile-app-7ab80',
    storageBucket: 'business-profile-app-7ab80.firebasestorage.app',
    iosClientId: '727175749515-h2v6plbhde561oinu8s4tcftr8h01qtq.apps.googleusercontent.com',
    iosBundleId: 'com.example.reviewmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKi8B1Yx7V8FzbXBz-Z8stj2Y8VRxkhP0',
    appId: '1:727175749515:web:3cb7775dd08e498254198e',
    messagingSenderId: '727175749515',
    projectId: 'business-profile-app-7ab80',
    authDomain: 'business-profile-app-7ab80.firebaseapp.com',
    storageBucket: 'business-profile-app-7ab80.firebasestorage.app',
    measurementId: 'G-K0LZ360RBD',
  );

}